Pages/Admin/AdminDashBoard.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ProjectBankApp.Pages.Admin
{
    public class AdminDashBoardModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Admin/AllUserProfile.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProjectBankApp.DataAccess;
using ProjectBankApp.Models;

namespace ProjectBankApp.Pages.Users
{
    public class AllUserProfileModel : PageModel
    {
        public List<UserProfileDataModel> UserProfileList { get; set; }
        public List<UserProfileDataModel> SearchList { get; set; }

        public string SuccessMessage { get; set; }
        public string ErrorMessage { get; set; }

        [BindProperty]
        public string SearchText { get; set; }

        public AllUserProfileModel()
        {
            SuccessMessage = "";
            ErrorMessage = "";
            SearchText = "";
            UserProfileList = new List<UserProfileDataModel>();
            SearchList = new List<UserProfileDataModel>();

        }


        public void OnGet()
        {
            var usersProfile = new UserDetailsDataAccess();
            UserProfileList = usersProfile.GetAllUserProfile();
        }



        public void OnPostSearch()
        {
            if (!ModelState.IsValid)
            {
                ErrorMessage = "Invalid DATA!!!!!";
                return;
            }

            if (string.IsNullOrEmpty(SearchText) || SearchText.Length < 2)
            {
                ErrorMessage = "Please Enter a string of length a minimum of 2 characters or more.";
                return;
            }

            var customerData = new UserDetailsDataAccess();
            UserProfileList = customerData.SearchByName(SearchText, SearchText);

            //if (Departments != null || Departments.Count > 0)

            if (UserProfileList != null && UserProfileList.Count > 0)
            {
                SuccessMessage = $"{UserProfileList.Count} data(s) Found";

            }
            else
            {
                ErrorMessage = "Sorry! No Data Found.";

            }
        }

        public void OnPostClear()
        {
            SearchText = "";
            ModelState.Clear();

            var customerData = new UserDetailsDataAccess();
            UserProfileList = customerData.SearchByName(SearchText, SearchText);


        }

    }
}

Pages/Admin/AllUserStatement.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProjectBankApp.DataAccess;
using ProjectBankApp.Models;

namespace ProjectBankApp.Pages.Admin
{
    public class AllUserStatementModel : PageModel
    {
        public List<UserStatementDataModel> UserStatementList { get; set; }

        public string SuccessMessage { get; set; }
        public string ErrorMessage { get; set; }

        [BindProperty]
        public string SearchText { get; set; }

        public AllUserStatementModel()
        {
            SuccessMessage = "";
            ErrorMessage = "";
            SearchText = "";
            UserStatementList = new List<UserStatementDataModel>();

        }


        public void OnGet()
        {
            var userTransaction = new UserDetailsDataAccess();
            UserStatementList = userTransaction.GetAllTransactions();
        }



        public void OnPostSearch()
        {
            //    if (!ModelState.IsValid)
            //    {
            //        ErrorMessage = "Invalid DATA!!!!!";
            //        return;
            //    }

            //    if (string.IsNullOrEmpty(SearchText) || SearchText.Length < 2)
            //    {
            //        ErrorMessage = "Please Enter a string of length a minimum of 2 characters or more.";
            //        return;
            //    }

            //    var customerData = new CustomerDataAccess();
            //    CustomerList = customerData.GetByName(SearchText, SearchText, SearchText, SearchText);

            //    //if (Departments != null || Departments.Count > 0)

            //    if (CustomerList != null && CustomerList.Count > 0)
            //    {
            //        SuccessMessage = $"{CustomerList.Count} data(s) Found";

            //    }
            //    else
            //    {
            //        ErrorMessage = "Sorry! No Data Found.";

            //    }
            //}

            //public void OnPostClear()
            //{
            //    SearchText = "";
            //    ModelState.Clear();

            //    var customerData = new CustomerDataAccess();
            //    CustomerList = customerData.GetByName(SearchText, SearchText, SearchText, SearchText);


        }

    }
}

Pages/Admin/AdminDashBoard.cshtml
@page
@model ProjectBankApp.Pages.Admin.AdminDashBoardModel
@{
}

Pages/Admin/AllUserProfile.cshtml
@page
@model ProjectBankApp.Pages.Users.AllUserProfileModel
@{
}

<form method="post">
    <div class="row form-group">
        <div class="col-sm-10"><h2>Customer Profiles </h2></div>
  
     
    </div>
    <div>
  
            <input type="text" asp-for="@Model.SearchText" style="width:1000px;border-radius: 50px" />

            <button type="submit" class="btn btn-success" asp-page-handler="Search">
                <i class="fa fa-search"></i>
            </button>

            <button type="submit" class="btn btn-success" asp-page-handler="Clear">
                <i class="fa fa-xmark"></i>
            </button>
        </div>
        <div>
        <h6 class="text-success">@Model.SuccessMessage </h6>
        <h6 class="text-danger">@Model.ErrorMessage </h6>
        </div>

        <table class="table" style="background-color:aqua">
            <thead>
                <tr>
                <th>Id</th>
                <th>First Name</th>
                <th>Middle Name</th>
                <th>Last Name</th>
                <th>DOB</th>
                <th>Gender</th>
                <th>AccountNo</th> 
                <th>AccountType</th> 
                <th>ACD</th> 
                <th>Current Balance</th>
                <th>Branch Name</th>
                <th> Branch IFSC Code</th>
                <th>Branch City</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Pincode</th>
                <th>Email Id</th>
                <th>Mobile Number</th>
                <th>Occupation</th>
                <th> Account Status</th>
                <th> Action</th>
             
                 </tr>
            </thead>

            <tbody>
                <tr>
                    @foreach (var g in @Model.UserProfileList)
                    {
                    <tr>
                        <td>@g.Id</td>
                        <td>@g.FirstName</td>
                        <td>@g.MiddleName</td>
                        <td>@g.LastName</td>
                        <td>@g.DOB</td>
                        <td>@g.Gender</td>
                        <td>@g.AccountNo</td> 
                        <td>@g.AccountType</td> 
                        <td>@g.ACD</td> 
                        <td>@g.CurrentBalance</td>
                        <td>@g.BranchName</td>
                        <td>@g.BranchIFSC</td>
                        <td>@g.BranchCity</td>
                        <td>@g.Address</td>
                        <td>@g.City</td>
                        <td>@g.State</td>
                        <td>@g.Pincode</td>
                        <td>@g.EmailId</td>
                        <td>@g.MobileNumber</td>
                        <td>@g.Occupation</td>
                        <td>@g.AccountStatus</td>
                      <td>

                            <a href="/Customers/Edit/@g.Id" class="btn btn-outline-warning" role="button">
                                <i class="fa fa-pen-to-square"></i>
                            </a>
                        
                        </td>
             
                       

                          
                  </tr>
                    }

            </tbody>

        </table>
</form>

Pages/Admin/AllUserStatement.cshtml
@page
@model ProjectBankApp.Pages.Admin.AllUserStatementModel
@{
}


<form method="post">
    <div class="row form-group">
        <div class="col-sm-10"><h2>Customer Profiles </h2></div>
  
       @* <div class="col-sm">
            <a href="/Customers/Add" class="btn btn-success rounded-pill" role="button">
                <i class="fa-solid fa-plus"></i> Add
            </a>
        </div>*@
    </div>
    <div>
  
           
        </div>
        <div>
        <h6 class="text-success">@Model.SuccessMessage </h6>
        <h6 class="text-danger">@Model.ErrorMessage </h6>
        </div>

        <table class="table" style="background-color:aqua">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Account Number</th>
                    <th>Account Holder</th>    
                    <th>Account Type</th>  
                     <th>Date of Transaction</th> 
                    <th>TransactonType</th> 
                      <th>Amount</th> 
                     <th>OpeningBalance</th> 
                     <th>ClosingBalance</th>  
                     <th>Remarks</th>  
                    
                   
                 </tr>
            </thead>

            <tbody>
                <tr>
                    @foreach (var g in @Model.UserStatementList)
                    {
                    <tr>
                        <td>@g.Id</td>
                        <td>@g.AccountNo</td>
                        <td>@g.AccountHolderName</td>
                        <td>@g.AccountType</td>
                        <td>@g.DOT</td>
                        <td>@g.TransactonType</td>
                        <td>@g.Amount</td> 
                        <td>@g.OpeningBalance</td> 
                        <td>@g.ClosingBalance</td> 
                        <td>@g.Remarks</td>
                       
             
                       

                          
                  </tr>
                    }

            </tbody>

        </table>
</form>